-- Copy và chạy toàn bộ đoạn code này trong phần SQL Editor của Supabase để sửa lỗi thiếu cột.

-- 1. Tạo bảng transactions nếu chưa có
CREATE TABLE IF NOT EXISTS transactions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id text,
    user_name text,
    amount bigint,
    coiz_reward bigint,
    trans_code text,
    method text,
    status text default 'pending',
    handled boolean default false,
    expires_at timestamp with time zone
);

-- 2. Thêm các cột còn thiếu (Nếu bảng đã có rồi nhưng thiếu cột)
DO $$
BEGIN
    -- Thêm cột 'method' (Phương thức thanh toán: MOMO, VNPAY...)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='method') THEN
        ALTER TABLE transactions ADD COLUMN method TEXT;
    END IF;

    -- Thêm cột 'handled' (Để check đã cộng tiền chưa)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='handled') THEN
        ALTER TABLE transactions ADD COLUMN handled BOOLEAN DEFAULT FALSE;
    END IF;

    -- Thêm cột 'coiz_reward' (Số tiền Coiz nhận được)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='coiz_reward') THEN
        ALTER TABLE transactions ADD COLUMN coiz_reward BIGINT DEFAULT 0;
    END IF;

    -- Thêm cột 'trans_code' (Mã giao dịch GUMZ...)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='trans_code') THEN
        ALTER TABLE transactions ADD COLUMN trans_code TEXT;
    END IF;

    -- Thêm cột 'status'
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='status') THEN
        ALTER TABLE transactions ADD COLUMN status TEXT DEFAULT 'pending';
    END IF;
    
     -- Thêm cột 'expires_at'
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='expires_at') THEN
        ALTER TABLE transactions ADD COLUMN expires_at TIMESTAMP WITH TIME ZONE;
    END IF;
    
    -- Thêm cột 'user_name'
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transactions' AND column_name='user_name') THEN
        ALTER TABLE transactions ADD COLUMN user_name TEXT;
    END IF;
END $$;
